package pojo;
// Generated Jan 28, 2018 6:35:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Assessment generated by hbm2java
 */
public class Assessment  implements java.io.Serializable {


     private Integer idAssessment;
     private Customer customer;
     private Street street;
     private String assessmentNo;
     private Integer status;
     private Integer syn;
     private Set<Application> applications = new HashSet<Application>(0);

    public Assessment() {
    }

	
    public Assessment(Customer customer, Street street) {
        this.customer = customer;
        this.street = street;
    }
    public Assessment(Customer customer, Street street, String assessmentNo, Integer status, Integer syn, Set<Application> applications) {
       this.customer = customer;
       this.street = street;
       this.assessmentNo = assessmentNo;
       this.status = status;
       this.syn = syn;
       this.applications = applications;
    }
   
    public Integer getIdAssessment() {
        return this.idAssessment;
    }
    
    public void setIdAssessment(Integer idAssessment) {
        this.idAssessment = idAssessment;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Street getStreet() {
        return this.street;
    }
    
    public void setStreet(Street street) {
        this.street = street;
    }
    public String getAssessmentNo() {
        return this.assessmentNo;
    }
    
    public void setAssessmentNo(String assessmentNo) {
        this.assessmentNo = assessmentNo;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }
    public Set<Application> getApplications() {
        return this.applications;
    }
    
    public void setApplications(Set<Application> applications) {
        this.applications = applications;
    }




}


