package pojo;
// Generated Jan 15, 2018 9:38:27 AM by Hibernate Tools 4.3.1



/**
 * CatagoryHasRo generated by hbm2java
 */
public class CatagoryHasRo  implements java.io.Serializable {


     private Integer idCatagoryHasRo;
     private Catagory catagory;
     private Ro ro;
     private Integer syn;

    public CatagoryHasRo() {
    }

	
    public CatagoryHasRo(Catagory catagory, Ro ro) {
        this.catagory = catagory;
        this.ro = ro;
    }
    public CatagoryHasRo(Catagory catagory, Ro ro, Integer syn) {
       this.catagory = catagory;
       this.ro = ro;
       this.syn = syn;
    }
   
    public Integer getIdCatagoryHasRo() {
        return this.idCatagoryHasRo;
    }
    
    public void setIdCatagoryHasRo(Integer idCatagoryHasRo) {
        this.idCatagoryHasRo = idCatagoryHasRo;
    }
    public Catagory getCatagory() {
        return this.catagory;
    }
    
    public void setCatagory(Catagory catagory) {
        this.catagory = catagory;
    }
    public Ro getRo() {
        return this.ro;
    }
    
    public void setRo(Ro ro) {
        this.ro = ro;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }




}


