package pojo;
// Generated Feb 16, 2018 8:45:58 AM by Hibernate Tools 4.3.1



/**
 * ChequeBank generated by hbm2java
 */
public class ChequeBank  implements java.io.Serializable {


     private Integer idChequeBank;
     private String bankName;

    public ChequeBank() {
    }

    public ChequeBank(String bankName) {
       this.bankName = bankName;
    }
   
    public Integer getIdChequeBank() {
        return this.idChequeBank;
    }
    
    public void setIdChequeBank(Integer idChequeBank) {
        this.idChequeBank = idChequeBank;
    }
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }




}


