package pojo;
// Generated Jan 18, 2018 5:44:14 PM by Hibernate Tools 4.3.1



/**
 * CustomerHasAssessment generated by hbm2java
 */
public class CustomerHasAssessment  implements java.io.Serializable {


     private Integer idCustomerHasAssessmentcol;
     private Assessment assessment;
     private Customer customer;
     private Integer syn;

    public CustomerHasAssessment() {
    }

	
    public CustomerHasAssessment(Assessment assessment, Customer customer) {
        this.assessment = assessment;
        this.customer = customer;
    }
    public CustomerHasAssessment(Assessment assessment, Customer customer, Integer syn) {
       this.assessment = assessment;
       this.customer = customer;
       this.syn = syn;
    }
   
    public Integer getIdCustomerHasAssessmentcol() {
        return this.idCustomerHasAssessmentcol;
    }
    
    public void setIdCustomerHasAssessmentcol(Integer idCustomerHasAssessmentcol) {
        this.idCustomerHasAssessmentcol = idCustomerHasAssessmentcol;
    }
    public Assessment getAssessment() {
        return this.assessment;
    }
    
    public void setAssessment(Assessment assessment) {
        this.assessment = assessment;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }




}


