package pojo;
// Generated Jan 18, 2018 5:16:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Otheritiscat generated by hbm2java
 */
public class Otheritiscat  implements java.io.Serializable {


     private Integer idOtheritisCat;
     private String catname;
     private String disignation;
     private Set<User> users = new HashSet<User>(0);

    public Otheritiscat() {
    }

    public Otheritiscat(String catname, String disignation, Set<User> users) {
       this.catname = catname;
       this.disignation = disignation;
       this.users = users;
    }
   
    public Integer getIdOtheritisCat() {
        return this.idOtheritisCat;
    }
    
    public void setIdOtheritisCat(Integer idOtheritisCat) {
        this.idOtheritisCat = idOtheritisCat;
    }
    public String getCatname() {
        return this.catname;
    }
    
    public void setCatname(String catname) {
        this.catname = catname;
    }
    public String getDisignation() {
        return this.disignation;
    }
    
    public void setDisignation(String disignation) {
        this.disignation = disignation;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


