package pojo;
// Generated Jan 19, 2018 11:37:25 PM by Hibernate Tools 4.3.1



/**
 * Otheritiscat generated by hbm2java
 */
public class Otheritiscat  implements java.io.Serializable {


     private Integer idOtheritisCat;
     private User user;
     private String catname;
     private String disignation;

    public Otheritiscat() {
    }

	
    public Otheritiscat(User user) {
        this.user = user;
    }
    public Otheritiscat(User user, String catname, String disignation) {
       this.user = user;
       this.catname = catname;
       this.disignation = disignation;
    }
   
    public Integer getIdOtheritisCat() {
        return this.idOtheritisCat;
    }
    
    public void setIdOtheritisCat(Integer idOtheritisCat) {
        this.idOtheritisCat = idOtheritisCat;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCatname() {
        return this.catname;
    }
    
    public void setCatname(String catname) {
        this.catname = catname;
    }
    public String getDisignation() {
        return this.disignation;
    }
    
    public void setDisignation(String disignation) {
        this.disignation = disignation;
    }




}


