package pojo;
// Generated Jan 15, 2018 9:38:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ro generated by hbm2java
 */
public class Ro  implements java.io.Serializable {


     private Integer idRo;
     private String roname;
     private String nic;
     private String mobile;
     private Integer statues;
     private String roNumber;
     private Integer status;
     private Integer syn;
     private Set<CatagoryHasRo> catagoryHasRos = new HashSet<CatagoryHasRo>(0);

    public Ro() {
    }

    public Ro(String roname, String nic, String mobile, Integer statues, String roNumber, Integer status, Integer syn, Set<CatagoryHasRo> catagoryHasRos) {
       this.roname = roname;
       this.nic = nic;
       this.mobile = mobile;
       this.statues = statues;
       this.roNumber = roNumber;
       this.status = status;
       this.syn = syn;
       this.catagoryHasRos = catagoryHasRos;
    }
   
    public Integer getIdRo() {
        return this.idRo;
    }
    
    public void setIdRo(Integer idRo) {
        this.idRo = idRo;
    }
    public String getRoname() {
        return this.roname;
    }
    
    public void setRoname(String roname) {
        this.roname = roname;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public Integer getStatues() {
        return this.statues;
    }
    
    public void setStatues(Integer statues) {
        this.statues = statues;
    }
    public String getRoNumber() {
        return this.roNumber;
    }
    
    public void setRoNumber(String roNumber) {
        this.roNumber = roNumber;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }
    public Set<CatagoryHasRo> getCatagoryHasRos() {
        return this.catagoryHasRos;
    }
    
    public void setCatagoryHasRos(Set<CatagoryHasRo> catagoryHasRos) {
        this.catagoryHasRos = catagoryHasRos;
    }




}


