package pojo;
// Generated Mar 14, 2018 12:29:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SrBuilding generated by hbm2java
 */
public class SrBuilding  implements java.io.Serializable {


     private Integer idBuilding;
     private Street street;
     private String buildingName;
     private Integer status;
     private Integer syn;
     private Set<SrFlow> srFlows = new HashSet<SrFlow>(0);

    public SrBuilding() {
    }

	
    public SrBuilding(Street street) {
        this.street = street;
    }
    public SrBuilding(Street street, String buildingName, Integer status, Integer syn, Set<SrFlow> srFlows) {
       this.street = street;
       this.buildingName = buildingName;
       this.status = status;
       this.syn = syn;
       this.srFlows = srFlows;
    }
   
    public Integer getIdBuilding() {
        return this.idBuilding;
    }
    
    public void setIdBuilding(Integer idBuilding) {
        this.idBuilding = idBuilding;
    }
    public Street getStreet() {
        return this.street;
    }
    
    public void setStreet(Street street) {
        this.street = street;
    }
    public String getBuildingName() {
        return this.buildingName;
    }
    
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }
    public Set<SrFlow> getSrFlows() {
        return this.srFlows;
    }
    
    public void setSrFlows(Set<SrFlow> srFlows) {
        this.srFlows = srFlows;
    }




}


