package pojo;
// Generated Mar 14, 2018 12:29:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SrFlow generated by hbm2java
 */
public class SrFlow  implements java.io.Serializable {


     private Integer idFlow;
     private SrBuilding srBuilding;
     private String flowName;
     private Integer status;
     private Integer syn;
     private Set<SrShopNo> srShopNos = new HashSet<SrShopNo>(0);

    public SrFlow() {
    }

	
    public SrFlow(SrBuilding srBuilding) {
        this.srBuilding = srBuilding;
    }
    public SrFlow(SrBuilding srBuilding, String flowName, Integer status, Integer syn, Set<SrShopNo> srShopNos) {
       this.srBuilding = srBuilding;
       this.flowName = flowName;
       this.status = status;
       this.syn = syn;
       this.srShopNos = srShopNos;
    }
   
    public Integer getIdFlow() {
        return this.idFlow;
    }
    
    public void setIdFlow(Integer idFlow) {
        this.idFlow = idFlow;
    }
    public SrBuilding getSrBuilding() {
        return this.srBuilding;
    }
    
    public void setSrBuilding(SrBuilding srBuilding) {
        this.srBuilding = srBuilding;
    }
    public String getFlowName() {
        return this.flowName;
    }
    
    public void setFlowName(String flowName) {
        this.flowName = flowName;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }
    public Set<SrShopNo> getSrShopNos() {
        return this.srShopNos;
    }
    
    public void setSrShopNos(Set<SrShopNo> srShopNos) {
        this.srShopNos = srShopNos;
    }




}


