package pojo;
// Generated Mar 14, 2018 12:29:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SrRentalType generated by hbm2java
 */
public class SrRentalType  implements java.io.Serializable {


     private Integer idRentalType;
     private String RType;
     private Integer status;
     private Integer syn;
     private Set<SrShopNo> srShopNos = new HashSet<SrShopNo>(0);

    public SrRentalType() {
    }

    public SrRentalType(String RType, Integer status, Integer syn, Set<SrShopNo> srShopNos) {
       this.RType = RType;
       this.status = status;
       this.syn = syn;
       this.srShopNos = srShopNos;
    }
   
    public Integer getIdRentalType() {
        return this.idRentalType;
    }
    
    public void setIdRentalType(Integer idRentalType) {
        this.idRentalType = idRentalType;
    }
    public String getRType() {
        return this.RType;
    }
    
    public void setRType(String RType) {
        this.RType = RType;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }
    public Set<SrShopNo> getSrShopNos() {
        return this.srShopNos;
    }
    
    public void setSrShopNos(Set<SrShopNo> srShopNos) {
        this.srShopNos = srShopNos;
    }




}


