package pojo;
// Generated Mar 14, 2018 12:29:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SrShopRentInfo generated by hbm2java
 */
public class SrShopRentInfo  implements java.io.Serializable {


     private Integer idShopRentInfo;
     private Customer customer;
     private SrShopNo srShopNo;
     private Double rentalStatic;
     private Double keyMoneyStatic;
     private Double currentRental;
     private Double currentKeymoney;
     private Double currentWarrant;
     private Date startDate;
     private Date endDate;
     private String shopRentInfocol;
     private Integer rentalTypeStatus;
     private Set<SrRental> srRentals = new HashSet<SrRental>(0);

    public SrShopRentInfo() {
    }

	
    public SrShopRentInfo(Customer customer, SrShopNo srShopNo) {
        this.customer = customer;
        this.srShopNo = srShopNo;
    }
    public SrShopRentInfo(Customer customer, SrShopNo srShopNo, Double rentalStatic, Double keyMoneyStatic, Double currentRental, Double currentKeymoney, Double currentWarrant, Date startDate, Date endDate, String shopRentInfocol, Integer rentalTypeStatus, Set<SrRental> srRentals) {
       this.customer = customer;
       this.srShopNo = srShopNo;
       this.rentalStatic = rentalStatic;
       this.keyMoneyStatic = keyMoneyStatic;
       this.currentRental = currentRental;
       this.currentKeymoney = currentKeymoney;
       this.currentWarrant = currentWarrant;
       this.startDate = startDate;
       this.endDate = endDate;
       this.shopRentInfocol = shopRentInfocol;
       this.rentalTypeStatus = rentalTypeStatus;
       this.srRentals = srRentals;
    }
   
    public Integer getIdShopRentInfo() {
        return this.idShopRentInfo;
    }
    
    public void setIdShopRentInfo(Integer idShopRentInfo) {
        this.idShopRentInfo = idShopRentInfo;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public SrShopNo getSrShopNo() {
        return this.srShopNo;
    }
    
    public void setSrShopNo(SrShopNo srShopNo) {
        this.srShopNo = srShopNo;
    }
    public Double getRentalStatic() {
        return this.rentalStatic;
    }
    
    public void setRentalStatic(Double rentalStatic) {
        this.rentalStatic = rentalStatic;
    }
    public Double getKeyMoneyStatic() {
        return this.keyMoneyStatic;
    }
    
    public void setKeyMoneyStatic(Double keyMoneyStatic) {
        this.keyMoneyStatic = keyMoneyStatic;
    }
    public Double getCurrentRental() {
        return this.currentRental;
    }
    
    public void setCurrentRental(Double currentRental) {
        this.currentRental = currentRental;
    }
    public Double getCurrentKeymoney() {
        return this.currentKeymoney;
    }
    
    public void setCurrentKeymoney(Double currentKeymoney) {
        this.currentKeymoney = currentKeymoney;
    }
    public Double getCurrentWarrant() {
        return this.currentWarrant;
    }
    
    public void setCurrentWarrant(Double currentWarrant) {
        this.currentWarrant = currentWarrant;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getShopRentInfocol() {
        return this.shopRentInfocol;
    }
    
    public void setShopRentInfocol(String shopRentInfocol) {
        this.shopRentInfocol = shopRentInfocol;
    }
    public Integer getRentalTypeStatus() {
        return this.rentalTypeStatus;
    }
    
    public void setRentalTypeStatus(Integer rentalTypeStatus) {
        this.rentalTypeStatus = rentalTypeStatus;
    }
    public Set<SrRental> getSrRentals() {
        return this.srRentals;
    }
    
    public void setSrRentals(Set<SrRental> srRentals) {
        this.srRentals = srRentals;
    }




}


