package pojo;
// Generated Mar 14, 2018 12:29:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SrShopNo generated by hbm2java
 */
public class SrShopNo  implements java.io.Serializable {


     private Integer idShopNo;
     private SrFlow srFlow;
     private SrRentalType srRentalType;
     private SrShopType srShopType;
     private String shopNo;
     private String tradeName;
     private Integer status;
     private Integer syn;
     private Set<SrShopRentInfo> srShopRentInfos = new HashSet<SrShopRentInfo>(0);

    public SrShopNo() {
    }

	
    public SrShopNo(SrFlow srFlow, SrRentalType srRentalType, SrShopType srShopType) {
        this.srFlow = srFlow;
        this.srRentalType = srRentalType;
        this.srShopType = srShopType;
    }
    public SrShopNo(SrFlow srFlow, SrRentalType srRentalType, SrShopType srShopType, String shopNo, String tradeName, Integer status, Integer syn, Set<SrShopRentInfo> srShopRentInfos) {
       this.srFlow = srFlow;
       this.srRentalType = srRentalType;
       this.srShopType = srShopType;
       this.shopNo = shopNo;
       this.tradeName = tradeName;
       this.status = status;
       this.syn = syn;
       this.srShopRentInfos = srShopRentInfos;
    }
   
    public Integer getIdShopNo() {
        return this.idShopNo;
    }
    
    public void setIdShopNo(Integer idShopNo) {
        this.idShopNo = idShopNo;
    }
    public SrFlow getSrFlow() {
        return this.srFlow;
    }
    
    public void setSrFlow(SrFlow srFlow) {
        this.srFlow = srFlow;
    }
    public SrRentalType getSrRentalType() {
        return this.srRentalType;
    }
    
    public void setSrRentalType(SrRentalType srRentalType) {
        this.srRentalType = srRentalType;
    }
    public SrShopType getSrShopType() {
        return this.srShopType;
    }
    
    public void setSrShopType(SrShopType srShopType) {
        this.srShopType = srShopType;
    }
    public String getShopNo() {
        return this.shopNo;
    }
    
    public void setShopNo(String shopNo) {
        this.shopNo = shopNo;
    }
    public String getTradeName() {
        return this.tradeName;
    }
    
    public void setTradeName(String tradeName) {
        this.tradeName = tradeName;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }
    public Set<SrShopRentInfo> getSrShopRentInfos() {
        return this.srShopRentInfos;
    }
    
    public void setSrShopRentInfos(Set<SrShopRentInfo> srShopRentInfos) {
        this.srShopRentInfos = srShopRentInfos;
    }




}


