package pojo;
// Generated Mar 14, 2018 12:29:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SrShopType generated by hbm2java
 */
public class SrShopType  implements java.io.Serializable {


     private Integer idShopType;
     private String shopType;
     private Integer status;
     private Integer syn;
     private Set<SrShopNo> srShopNos = new HashSet<SrShopNo>(0);

    public SrShopType() {
    }

    public SrShopType(String shopType, Integer status, Integer syn, Set<SrShopNo> srShopNos) {
       this.shopType = shopType;
       this.status = status;
       this.syn = syn;
       this.srShopNos = srShopNos;
    }
   
    public Integer getIdShopType() {
        return this.idShopType;
    }
    
    public void setIdShopType(Integer idShopType) {
        this.idShopType = idShopType;
    }
    public String getShopType() {
        return this.shopType;
    }
    
    public void setShopType(String shopType) {
        this.shopType = shopType;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }
    public Set<SrShopNo> getSrShopNos() {
        return this.srShopNos;
    }
    
    public void setSrShopNos(Set<SrShopNo> srShopNos) {
        this.srShopNos = srShopNos;
    }




}


