package pojo;
// Generated Jan 19, 2018 11:37:25 PM by Hibernate Tools 4.3.1



/**
 * TaxValue generated by hbm2java
 */
public class TaxValue  implements java.io.Serializable {


     private Integer idTaxValue;

    public TaxValue() {
    }

   
    public Integer getIdTaxValue() {
        return this.idTaxValue;
    }
    
    public void setIdTaxValue(Integer idTaxValue) {
        this.idTaxValue = idTaxValue;
    }




}


