package pojo;
// Generated Jan 20, 2018 8:59:03 AM by Hibernate Tools 4.3.1



/**
 * TaxValue generated by hbm2java
 */
public class TaxValue  implements java.io.Serializable {


     private Integer idTaxValue;

    public TaxValue() {
    }

   
    public Integer getIdTaxValue() {
        return this.idTaxValue;
    }
    
    public void setIdTaxValue(Integer idTaxValue) {
        this.idTaxValue = idTaxValue;
    }




}


