package pojo;
// Generated Jan 20, 2018 9:51:37 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TradeLicense generated by hbm2java
 */
public class TradeLicense  implements java.io.Serializable {


     private Integer idTradeLicense;
     private Payment payment;
     private String licenNo;
     private String tradeLicensecol;
     private Date tradeLicenseDate;
     private String tradeLicensecol1;
     private String tradeLicensecol2;
     private Integer status;
     private Integer syn;
     private Set<CustomerHasTradeLicense> customerHasTradeLicenses = new HashSet<CustomerHasTradeLicense>(0);

    public TradeLicense() {
    }

	
    public TradeLicense(Payment payment) {
        this.payment = payment;
    }
    public TradeLicense(Payment payment, String licenNo, String tradeLicensecol, Date tradeLicenseDate, String tradeLicensecol1, String tradeLicensecol2, Integer status, Integer syn, Set<CustomerHasTradeLicense> customerHasTradeLicenses) {
       this.payment = payment;
       this.licenNo = licenNo;
       this.tradeLicensecol = tradeLicensecol;
       this.tradeLicenseDate = tradeLicenseDate;
       this.tradeLicensecol1 = tradeLicensecol1;
       this.tradeLicensecol2 = tradeLicensecol2;
       this.status = status;
       this.syn = syn;
       this.customerHasTradeLicenses = customerHasTradeLicenses;
    }
   
    public Integer getIdTradeLicense() {
        return this.idTradeLicense;
    }
    
    public void setIdTradeLicense(Integer idTradeLicense) {
        this.idTradeLicense = idTradeLicense;
    }
    public Payment getPayment() {
        return this.payment;
    }
    
    public void setPayment(Payment payment) {
        this.payment = payment;
    }
    public String getLicenNo() {
        return this.licenNo;
    }
    
    public void setLicenNo(String licenNo) {
        this.licenNo = licenNo;
    }
    public String getTradeLicensecol() {
        return this.tradeLicensecol;
    }
    
    public void setTradeLicensecol(String tradeLicensecol) {
        this.tradeLicensecol = tradeLicensecol;
    }
    public Date getTradeLicenseDate() {
        return this.tradeLicenseDate;
    }
    
    public void setTradeLicenseDate(Date tradeLicenseDate) {
        this.tradeLicenseDate = tradeLicenseDate;
    }
    public String getTradeLicensecol1() {
        return this.tradeLicensecol1;
    }
    
    public void setTradeLicensecol1(String tradeLicensecol1) {
        this.tradeLicensecol1 = tradeLicensecol1;
    }
    public String getTradeLicensecol2() {
        return this.tradeLicensecol2;
    }
    
    public void setTradeLicensecol2(String tradeLicensecol2) {
        this.tradeLicensecol2 = tradeLicensecol2;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }
    public Set<CustomerHasTradeLicense> getCustomerHasTradeLicenses() {
        return this.customerHasTradeLicenses;
    }
    
    public void setCustomerHasTradeLicenses(Set<CustomerHasTradeLicense> customerHasTradeLicenses) {
        this.customerHasTradeLicenses = customerHasTradeLicenses;
    }




}


