package pojo;
// Generated Jan 25, 2018 12:13:56 PM by Hibernate Tools 4.3.1



/**
 * TradelicensRate generated by hbm2java
 */
public class TradelicensRate  implements java.io.Serializable {


     private Integer idTradeLicensRate;
     private Double min;
     private Double max;
     private Double rate;
     private Integer status;

    public TradelicensRate() {
    }

    public TradelicensRate(Double min, Double max, Double rate, Integer status) {
       this.min = min;
       this.max = max;
       this.rate = rate;
       this.status = status;
    }
   
    public Integer getIdTradeLicensRate() {
        return this.idTradeLicensRate;
    }
    
    public void setIdTradeLicensRate(Integer idTradeLicensRate) {
        this.idTradeLicensRate = idTradeLicensRate;
    }
    public Double getMin() {
        return this.min;
    }
    
    public void setMin(Double min) {
        this.min = min;
    }
    public Double getMax() {
        return this.max;
    }
    
    public void setMax(Double max) {
        this.max = max;
    }
    public Double getRate() {
        return this.rate;
    }
    
    public void setRate(Double rate) {
        this.rate = rate;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


