package pojo;
// Generated Jan 15, 2018 9:38:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserLog generated by hbm2java
 */
public class UserLog  implements java.io.Serializable {


     private Integer idUserLog;
     private User user;
     private Date outTyme;
     private Date inTyme;
     private Integer status;
     private Integer syn;
     private Set<Customer> customers = new HashSet<Customer>(0);

    public UserLog() {
    }

	
    public UserLog(User user) {
        this.user = user;
    }
    public UserLog(User user, Date outTyme, Date inTyme, Integer status, Integer syn, Set<Customer> customers) {
       this.user = user;
       this.outTyme = outTyme;
       this.inTyme = inTyme;
       this.status = status;
       this.syn = syn;
       this.customers = customers;
    }
   
    public Integer getIdUserLog() {
        return this.idUserLog;
    }
    
    public void setIdUserLog(Integer idUserLog) {
        this.idUserLog = idUserLog;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getOutTyme() {
        return this.outTyme;
    }
    
    public void setOutTyme(Date outTyme) {
        this.outTyme = outTyme;
    }
    public Date getInTyme() {
        return this.inTyme;
    }
    
    public void setInTyme(Date inTyme) {
        this.inTyme = inTyme;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getSyn() {
        return this.syn;
    }
    
    public void setSyn(Integer syn) {
        this.syn = syn;
    }
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }




}


